// Banco editable para Ahorcado
// Edita este archivo en GitHub para agregar categorías o palabras.
// Luego guarda con Commit changes.

window.ESL_WORD_BANKS = window.ESL_WORD_BANKS || {};
window.ESL_CATEGORY_LEVELS = window.ESL_CATEGORY_LEVELS || {};

window.ESL_WORD_BANKS["ahorcado"] = {
      "Numbers and time": [
            "zero",
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",
            "eleven",
            "twelve",
            "thirteen",
            "fourteen",
            "fifteen",
            "sixteen",
            "seventeen",
            "eighteen",
            "nineteen",
            "twenty",
            "twenty-four",
            "It's eight o'clock.",
            "It's four-thirty.",
            "It's a quarter to twelve.",
            "It's a quarter to one.",
            "It's three forty-five.",
            "It's nine-fifteen."
      ],
      "Inglés III__WB_LEVEL__JOBS": [
            "chef",
            "engineer",
            "nurse",
            "mechanic",
            "office worker",
            "receptionist",
            "sales assistant",
            "tour guide"
      ],
      "Workplaces": [
            "factory",
            "garage",
            "hotel reception",
            "office",
            "tour bus",
            "hospital",
            "kitchen",
            "store"
      ],
      "Nationalities and languages": [
            "American",
            "British",
            "Canadian",
            "Chinese",
            "Japanese",
            "Mexican",
            "Vietnamese",
            "Spanish"
      ],
      "Daily activities": [
            "check my emails",
            "finish work",
            "get dressed",
            "get home",
            "get up",
            "go to bed",
            "go to the gym",
            "go to work",
            "take a nap",
            "take a shower",
            "have breakfast",
            "start work"
      ],
      "Other daily routine phrases": [
            "check my phone",
            "check my messages",
            "go to school",
            "go to class",
            "have lunch",
            "have dinner",
            "start school",
            "finish school",
            "start college",
            "finish college"
      ],
      "Friends and family": [
            "boyfriend",
            "girlfriend",
            "colleague",
            "neighbor",
            "father",
            "mother",
            "brother",
            "sister",
            "uncle",
            "aunt",
            "cousin",
            "grandson",
            "granddaughter",
            "grandparents",
            "grandpa",
            "grandma"
      ],
      "Pets": [
            "bird",
            "cat",
            "dog",
            "rabbit"
      ],
      "Places to live": [
            "apartment",
            "flat",
            "house",
            "building"
      ],
      "Breakfast": [
            "boiled egg",
            "cereal",
            "fried egg",
            "toast",
            "yogurt",
            "coffee",
            "orange juice"
      ],
      "Inglés III__WB_LEVEL__FURNITURE": [
            "armchair",
            "cabinet",
            "couch",
            "lamp",
            "light",
            "shelf",
            "shelves",
            "sofa",
            "stove"
      ],
      "Parts of a house": [
            "ceiling",
            "deck",
            "floor",
            "staircase",
            "stairs",
            "wall",
            "dining room",
            "garage",
            "living room"
      ],
      "Food": [
            "bananas",
            "beans",
            "carrots",
            "cheese",
            "chips",
            "eggs",
            "onions",
            "pasta",
            "rice",
            "tomatoes"
      ],
      "Other food words": [
            "boil",
            "fresh",
            "frozen",
            "fry",
            "ingredient"
      ],
      "Transportation": [
            "bike",
            "bus",
            "motorcycle",
            "motorbike",
            "streetcar",
            "tram",
            "subway",
            "underground",
            "car",
            "drive",
            "on foot",
            "plane",
            "taxi",
            "train",
            "walk"
      ],
      "Verb phrases: skills": [
            "play the piano",
            "speak another language",
            "create an app",
            "ride a horse",
            "drive a car",
            "cook Thai food",
            "fly a kite",
            "tell jokes"
      ],
      "Verbs and prepositions to / about / at": [
            "chat to",
            "chat with",
            "listen to",
            "speak to",
            "talk to",
            "ask about",
            "speak about",
            "talk about",
            "think about",
            "arrive at",
            "look at"
      ],
      "Inglés III__WB_LEVEL__CLOTHES": [
            "coat",
            "raincoat",
            "dress",
            "jacket",
            "jeans",
            "sweater",
            "jumper",
            "scarf",
            "shirt",
            "skirt",
            "socks",
            "tights",
            "top",
            "sneakers",
            "trainers",
            "pants",
            "trousers",
            "T-shirt"
      ],
      "Inglés III__WB_LEVEL__COLORS": [
            "black",
            "dark blue",
            "light green",
            "orange",
            "pink",
            "purple",
            "red",
            "yellow"
      ],
      "Sports": [
            "biking",
            "climbing",
            "golf",
            "horseback riding",
            "ice skating",
            "running",
            "sailing",
            "skiing",
            "snowboarding",
            "surfing",
            "swimming",
            "walking"
      ],
      "Music": [
            "band",
            "dancer",
            "fan",
            "guitar player",
            "instrument",
            "piano player",
            "singer",
            "artist",
            "song",
            "songwriter"
      ],
      "Music styles": [
            "blues",
            "classical",
            "jazz",
            "pop",
            "rock",
            "soul"
      ],
      "Inglés III__WB_LEVEL__PREPOSITIONS OF PLACE": [
            "above",
            "across from",
            "behind",
            "between",
            "in front of",
            "inside",
            "next to",
            "on",
            "under"
      ],
      "Inglés III__WB_LEVEL__MONTHS": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
      ],
      "Inglés III__WB_LEVEL__ORDINAL NUMBERS": [
            "first",
            "second",
            "third",
            "fourth",
            "fifth",
            "sixth",
            "seventh",
            "eighth",
            "ninth",
            "tenth",
            "eleventh",
            "twelfth",
            "thirteenth",
            "fourteenth",
            "fifteenth",
            "sixteenth",
            "seventeenth",
            "eighteenth",
            "nineteenth",
            "twentieth",
            "twenty-first",
            "twenty-second",
            "twenty-third",
            "twenty-fourth",
            "twenty-fifth",
            "twenty-sixth",
            "twenty-seventh",
            "twenty-eighth",
            "twenty-ninth",
            "thirtieth",
            "thirty-first"
      ],
      "Inglés III__WB_LEVEL__PAST TIME EXPRESSIONS": [
            "in the morning",
            "in the afternoon",
            "in the evening",
            "on the weekend",
            "on Monday",
            "on Wednesday morning",
            "last night",
            "last week",
            "last year",
            "an hour ago",
            "two days ago",
            "a month ago",
            "yesterday morning",
            "for an hour",
            "for two days",
            "for three months"
      ],
      "Feelings": [
            "afraid",
            "angry",
            "bored",
            "disappointed",
            "excited",
            "nervous",
            "surprised",
            "worried"
      ],
      "Inglés IV__WB_LEVEL__OPINION ADJECTIVES": [
            "all right",
            "amazing",
            "awful",
            "boring",
            "excellent",
            "fantastic",
            "fine",
            "great",
            "horrible",
            "terrible",
            "wonderful"
      ],
      "Inglés IV__WB_LEVEL__NAMES": [
            "brand name",
            "full name",
            "initials",
            "nickname",
            "pen name",
            "real name",
            "stage name",
            "first name",
            "middle name",
            "last name"
      ],
      "Inglés IV__WB_LEVEL__FUTURE TIME EXPRESSIONS": [
            "after this",
            "after the class",
            "later",
            "this afternoon",
            "this evening",
            "tonight",
            "tomorrow morning",
            "tomorrow afternoon",
            "tomorrow night",
            "this weekend",
            "next week",
            "next month",
            "next year"
      ],
      "Inglés IV__WB_LEVEL__NATURE": [
            "branch",
            "forest",
            "grass",
            "hill",
            "leaf",
            "mountain",
            "sky",
            "tree",
            "woods"
      ],
      "Inglés IV__WB_LEVEL__OTHER NATURE WORDS": [
            "country",
            "countryside",
            "nature",
            "outdoors"
      ],
      "Inglés IV__WB_LEVEL__WEATHER": [
            "cloudy",
            "cold",
            "hot",
            "raining",
            "snowing",
            "sunny",
            "warm",
            "windy",
            "cloud",
            "rain",
            "snow",
            "sun",
            "wind",
            "rainy",
            "snowy"
      ],
      "Inglés IV__WB_LEVEL__FESTIVALS": [
            "balloon",
            "band",
            "costume",
            "decoration",
            "firework display",
            "live music",
            "parade",
            "present",
            "traditional meal",
            "traditional song"
      ],
      "Inglés IV__WB_LEVEL__ADVERBS OF MANNER": [
            "angrily",
            "carefully",
            "clearly",
            "happily",
            "immediately",
            "nicely",
            "politely",
            "quickly",
            "quietly",
            "safely",
            "slowly",
            "well"
      ],
      "Inglés IV__WB_LEVEL__HEALTH AND BODY": [
            "arm",
            "back",
            "ear",
            "eye",
            "fingers",
            "foot",
            "head",
            "leg",
            "mouth",
            "neck",
            "nose",
            "toes",
            "headache",
            "back pain",
            "stomachache",
            "health",
            "mind",
            "voice"
      ],
      "Inglés IV__WB_LEVEL__PERSONALITY ADJECTIVES": [
            "friendly",
            "funny",
            "honest",
            "kind",
            "lazy",
            "polite",
            "quiet",
            "serious"
      ],
      "Inglés IV__WB_LEVEL__TECHNOLOGY": [
            "battery",
            "cable",
            "charger",
            "headphones",
            "keyboard",
            "laptop",
            "microphone",
            "mouse",
            "PC",
            "printer",
            "screen",
            "speaker"
      ],
      "Inglés IV__WB_LEVEL__READING AND WRITING": [
            "calendar",
            "comic",
            "diary",
            "handwriting",
            "ink",
            "magazine",
            "notebook",
            "pen"
      ],
      "Inglés IV__WB_LEVEL__OTHER READING AND WRITING WORDS": [
            "author",
            "writer",
            "biography",
            "blog",
            "fiction",
            "non-fiction",
            "journal",
            "page"
      ],
      "Inglés IV__WB_LEVEL__HOUSEWORK / CHORES": [
            "do the laundry",
            "do the washing",
            "dust",
            "set the table",
            "lay the table",
            "make the bed",
            "take out the garbage",
            "take out the rubbish",
            "clean up",
            "tidy up",
            "vacuum",
            "do the dishes",
            "do the washing up"
      ],
      "Inglés IV__WB_LEVEL__LIFE EVENTS": [
            "become a grandparent",
            "find a job",
            "finish school",
            "get married",
            "go to college",
            "have children",
            "learn to drive",
            "leave home",
            "meet a partner",
            "retire",
            "vote"
      ],
      "Inglés IV__WB_LEVEL__EATING OUT": [
            "affordable",
            "appetizer",
            "bill",
            "check",
            "cooking",
            "dessert",
            "eat out",
            "entree",
            "menu",
            "order",
            "tip"
      ],
      "Inglés IV__WB_LEVEL__VERB PHRASES / EXPERIENCES": [
            "eat sushi",
            "go to Boston",
            "make bread",
            "meet a famous person",
            "play Sudoku",
            "read a book in English",
            "see a ghost",
            "win a prize"
      ],
      "Inglés IV__WB_LEVEL__MOVIES AND TV": [
            "adventure",
            "comedy",
            "documentary",
            "horror",
            "science fiction",
            "western"
      ],
      "Inglés IV__WB_LEVEL__OTHER MOVIE AND TV WORDS": [
            "audience",
            "character",
            "episode",
            "screen",
            "series",
            "scene"
      ],
      "Inglés IV__WB_LEVEL__SPORTS COMPETITIONS": [
            "championship",
            "competition",
            "final",
            "game",
            "lose",
            "match",
            "play",
            "pro",
            "team",
            "win",
            "winner"
      ],
      "Inglés IV__WB_LEVEL__JOBS": [
            "actor",
            "computer programmer",
            "film director",
            "server",
            "waiter",
            "waitress"
      ],
      "Inglés IV__WB_LEVEL__HOBBIES & SKILLS": [
            "going to concerts",
            "photography",
            "playing video games"
      ],
      "Inglés IV__WB_LEVEL__STUDIES": [
            "biology",
            "drama"
      ],
      "Inglés IV__WB_LEVEL__PERSONAL INFORMATION EXPRESSIONS": [
            "work as a",
            "I have always wanted to be",
            "study biology in college",
            "take a course",
            "My main hobby is",
            "In my free time I like"
      ],
      "Different things": [
            "apple",
            "book",
            "coffee",
            "guitar",
            "pen",
            "taxi",
            "zebra"
      ],
      "Colors": [
            "black",
            "blue",
            "brown",
            "green",
            "orange",
            "red",
            "white",
            "yellow"
      ],
      "Days of the week": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday"
      ],
      "Numbers 0-10": [
            "zero",
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten"
      ],
      "Personal information 1": [
            "email address",
            "first name",
            "last name",
            "phone number"
      ],
      "Countries": [
            "Brazil",
            "Chile",
            "Egypt",
            "England",
            "Italy",
            "Russia",
            "Turkey",
            "the United States"
      ],
      "Numbers 11-100": [
            "eleven",
            "twelve",
            "thirteen",
            "fourteen",
            "fifteen",
            "sixteen",
            "seventeen",
            "eighteen",
            "nineteen",
            "twenty",
            "twenty-one",
            "twenty-two",
            "twenty-three",
            "twenty-four",
            "twenty-five",
            "twenty-six",
            "twenty-seven",
            "twenty-eight",
            "twenty-nine",
            "thirty",
            "forty",
            "fifty",
            "sixty",
            "seventy",
            "eighty",
            "ninety",
            "one hundred"
      ],
      "Personal information 2": [
            "address",
            "city",
            "country",
            "name",
            "title",
            "town",
            "zip code"
      ],
      "Technology": [
            "alarm clock",
            "camera",
            "computer",
            "games console",
            "phone",
            "radio",
            "tablet",
            "TV",
            "video games",
            "watch"
      ],
      "Months": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
      ],
      "Ordinal numbers": [
            "first",
            "second",
            "third",
            "fourth",
            "fifth",
            "sixth",
            "seventh",
            "eighth",
            "ninth",
            "tenth",
            "eleventh",
            "twelfth",
            "thirteenth",
            "fourteenth",
            "fifteenth",
            "sixteenth",
            "seventeenth",
            "eighteenth",
            "nineteenth",
            "twentieth",
            "twenty-first",
            "twenty-second",
            "twenty-third",
            "twenty-fourth",
            "twenty-fifth",
            "twenty-sixth",
            "twenty-seventh",
            "twenty-eighth",
            "twenty-ninth",
            "thirtieth",
            "thirty-first"
      ],
      "Snacks and drinks": [
            "black coffee",
            "chips",
            "chocolate bars",
            "coffee with milk",
            "cookies",
            "hot chocolate",
            "milk",
            "orange juice",
            "sandwiches",
            "soda",
            "tea",
            "water"
      ],
      "Rooms": [
            "bathroom",
            "bedroom",
            "kitchen",
            "living room"
      ],
      "Furniture": [
            "bed",
            "chair",
            "couch",
            "shower",
            "table",
            "window"
      ],
      "Family": [
            "brother",
            "dad",
            "daughter",
            "father",
            "friend",
            "mom",
            "mother",
            "parents",
            "pet",
            "sister",
            "son"
      ],
      "Daily routines": [
            "finish class",
            "finish work",
            "get home",
            "get up",
            "go to bed",
            "go to class",
            "go to work",
            "have a shower",
            "have breakfast",
            "have dinner",
            "have lunch",
            "leave home",
            "start class",
            "start work",
            "wake up"
      ],
      "Sports and exercise": [
            "exercise",
            "play basketball",
            "play soccer",
            "play tennis",
            "ride a bike",
            "run",
            "swim",
            "walk",
            "walk your dog"
      ],
      "Verbs and prepositions": [
            "come from",
            "listen to",
            "live in",
            "love",
            "talk about",
            "work for",
            "work in"
      ],
      "Adjectives": [
            "boring",
            "difficult",
            "easy",
            "happy",
            "horrible",
            "interesting",
            "nice",
            "right",
            "sad",
            "wrong"
      ],
      "Inglés II__WB_LEVEL__ADVERBS OF FREQUENCY": [
            {
                  "en": "always",
                  "es": "siempre"
            },
            {
                  "en": "usually",
                  "es": "usualmente"
            },
            {
                  "en": "sometimes",
                  "es": "a veces"
            },
            {
                  "en": "never",
                  "es": "nunca"
            },
            {
                  "en": "often",
                  "es": "a menudo"
            }
      ],
      "Nationalities": [
            "American",
            "Chinese",
            "English",
            "Indian",
            "Italian",
            "Mexican",
            "Thai",
            "Turkish"
      ],
      "Free-time activities": [
            "Dancing",
            "going to the movies",
            "meeting friends",
            "playing video games",
            "reading",
            "shopping",
            "talking on the phone",
            "watching TV"
      ],
      "Parts of the body": [
            "arm",
            "ear",
            "eye",
            "face",
            "foot",
            "hand",
            "head",
            "leg",
            "mouth",
            "nose"
      ],
      "Clothes": [
            "dress",
            "jacket",
            "jeans",
            "pants",
            "shirt",
            "shoes",
            "shorts",
            "skirt",
            "T-shirt",
            "tie",
            "trousers"
      ],
      "Skills": [
            "cook",
            "dance",
            "draw",
            "paint",
            "play chess",
            "play the guitar",
            "sing",
            "speak Spanish",
            "write a computer program"
      ],
      "Prepositions of place": [
            "behind",
            "between",
            "in",
            "in front of",
            "near",
            "next to",
            "on",
            "under"
      ],
      "Places in a town": [
            "bank",
            "café",
            "clothing store",
            "coffee shop",
            "hospital",
            "parking lot",
            "restaurant",
            "school",
            "train station",
            "supermarket"
      ],
      "Jobs": [
            "actor",
            "baker",
            "doctor",
            "taxi driver",
            "lawyer",
            "musician",
            "nurse",
            "server",
            "teacher",
            "tennis player",
            "waiter",
            "waitress"
      ],
      "Past time expressions": [
            "four hours ago",
            "last month",
            "last night",
            "last weekend",
            "last week",
            "last year",
            "this afternoon",
            "this morning",
            "two weeks ago",
            "yesterday",
            "yesterday afternoon",
            "yesterday evening",
            "yesterday morning"
      ],
      "Verb phrases: celebrating": [
            "go out to dinner",
            "go out with friends",
            "go to a barbecue",
            "go to a concert",
            "go to a party",
            "go to a restaurant",
            "have a barbecue",
            "have a good time",
            "have a party",
            "have fun"
      ],
      "Review categories": [
            "clothes",
            "colors",
            "countries",
            "drinks",
            "family",
            "furniture",
            "jobs",
            "parts of the body",
            "places in a town",
            "technology"
      ],
      "Studio channels": [
            "arts",
            "entertainment",
            "business",
            "earth",
            "education",
            "food",
            "history",
            "living",
            "people",
            "science",
            "technology",
            "sports",
            "style",
            "travel"
      ],
      "Inglés II__WB_LEVEL__TRANSPORTATION AND": [
            "travel",
            "drive a car",
            "fly a plane",
            "go by train",
            "take a taxi",
            "travel by bus",
            "stay in a hotel",
            "visit New York"
      ]
};

window.ESL_CATEGORY_LEVELS["ahorcado"] = {
      "Inglés III__WB_LEVEL__JOBS": "Inglés III",
      "Inglés III__WB_LEVEL__FURNITURE": "Inglés III",
      "Inglés III__WB_LEVEL__CLOTHES": "Inglés III",
      "Inglés III__WB_LEVEL__COLORS": "Inglés III",
      "Inglés III__WB_LEVEL__PREPOSITIONS OF PLACE": "Inglés III",
      "Inglés III__WB_LEVEL__MONTHS": "Inglés III",
      "Inglés III__WB_LEVEL__ORDINAL NUMBERS": "Inglés III",
      "Inglés III__WB_LEVEL__PAST TIME EXPRESSIONS": "Inglés III",
      "Numbers and time": "Inglés III",
      "Workplaces": "Inglés III",
      "Nationalities and languages": "Inglés III",
      "Daily activities": "Inglés III",
      "Other daily routine phrases": "Inglés III",
      "Friends and family": "Inglés III",
      "Pets": "Inglés III",
      "Places to live": "Inglés III",
      "Breakfast": "Inglés III",
      "Parts of a house": "Inglés III",
      "Food": "Inglés III",
      "Other food words": "Inglés III",
      "Transportation": "Inglés III",
      "Verb phrases: skills": "Inglés III",
      "Verbs and prepositions to / about / at": "Inglés III",
      "Sports": "Inglés III",
      "Music": "Inglés III",
      "Music styles": "Inglés III",
      "Feelings": "Inglés III",
      "Inglés IV__WB_LEVEL__OPINION ADJECTIVES": "Inglés IV",
      "Inglés IV__WB_LEVEL__NAMES": "Inglés IV",
      "Inglés IV__WB_LEVEL__FUTURE TIME EXPRESSIONS": "Inglés IV",
      "Inglés IV__WB_LEVEL__NATURE": "Inglés IV",
      "Inglés IV__WB_LEVEL__OTHER NATURE WORDS": "Inglés IV",
      "Inglés IV__WB_LEVEL__WEATHER": "Inglés IV",
      "Inglés IV__WB_LEVEL__FESTIVALS": "Inglés IV",
      "Inglés IV__WB_LEVEL__ADVERBS OF MANNER": "Inglés IV",
      "Inglés IV__WB_LEVEL__HEALTH AND BODY": "Inglés IV",
      "Inglés IV__WB_LEVEL__PERSONALITY ADJECTIVES": "Inglés IV",
      "Inglés IV__WB_LEVEL__TECHNOLOGY": "Inglés IV",
      "Inglés IV__WB_LEVEL__READING AND WRITING": "Inglés IV",
      "Inglés IV__WB_LEVEL__OTHER READING AND WRITING WORDS": "Inglés IV",
      "Inglés IV__WB_LEVEL__HOUSEWORK / CHORES": "Inglés IV",
      "Inglés IV__WB_LEVEL__LIFE EVENTS": "Inglés IV",
      "Inglés IV__WB_LEVEL__EATING OUT": "Inglés IV",
      "Inglés IV__WB_LEVEL__VERB PHRASES / EXPERIENCES": "Inglés IV",
      "Inglés IV__WB_LEVEL__MOVIES AND TV": "Inglés IV",
      "Inglés IV__WB_LEVEL__OTHER MOVIE AND TV WORDS": "Inglés IV",
      "Inglés IV__WB_LEVEL__SPORTS COMPETITIONS": "Inglés IV",
      "Inglés IV__WB_LEVEL__JOBS": "Inglés IV",
      "Inglés IV__WB_LEVEL__HOBBIES & SKILLS": "Inglés IV",
      "Inglés IV__WB_LEVEL__STUDIES": "Inglés IV",
      "Inglés IV__WB_LEVEL__PERSONAL INFORMATION EXPRESSIONS": "Inglés IV",
      "Different things": "Inglés I",
      "Colors": "Inglés I",
      "Days of the week": "Inglés I",
      "Numbers 0-10": "Inglés I",
      "Personal information 1": "Inglés I",
      "Countries": "Inglés I",
      "Numbers 11-100": "Inglés I",
      "Personal information 2": "Inglés I",
      "Technology": "Inglés I",
      "Months": "Inglés I",
      "Ordinal numbers": "Inglés I",
      "Snacks and drinks": "Inglés I",
      "Rooms": "Inglés I",
      "Furniture": "Inglés I",
      "Family": "Inglés I",
      "Daily routines": "Inglés I",
      "Sports and exercise": "Inglés I",
      "Verbs and prepositions": "Inglés I",
      "Adjectives": "Inglés I",
      "Inglés II__WB_LEVEL__ADVERBS OF FREQUENCY": "Inglés II",
      "Nationalities": "Inglés II",
      "Free-time activities": "Inglés II",
      "Parts of the body": "Inglés II",
      "Clothes": "Inglés II",
      "Skills": "Inglés II",
      "Prepositions of place": "Inglés II",
      "Places in a town": "Inglés II",
      "Jobs": "Inglés II",
      "Past time expressions": "Inglés II",
      "Verb phrases: celebrating": "Inglés II",
      "Review categories": "Inglés II",
      "Studio channels": "Inglés II",
      "Inglés II__WB_LEVEL__TRANSPORTATION AND": "Inglés II"
};
